# Systean Lexical Categories (TOML Specification)

# Types
# Noun (N)
# RelativePronoun (RPron)
# PersonalPronoun (PPron)
# Verb (V)
# ImperativeVerb (IV)
# Auxiliary (Aux)
# Adjective (Adj)
# Adverb (Adv)
# Preposition (P)
# Determiner (Det)
# QuestionParticle (QPart)
# ImperativeParticle (IPart)
# Conjunction (Conj) 
# SubordinatingConjunction (SubConj)
# Nesting (Nest) remain in the same nesting, return to the highest nesting, increase nesting by one, decrease nesting by one, etc.

# \+: many or zero
# \*: many (at least one)
# \?: optional
# |: or

# # Sentence
# S → SentP
# | QuestionParticle SentP
# | ImperativeParticle IVP NP SubClause?

# SubClause → SubConj SentP

# SentP -> SubClause? NP VP P? NP (Nest? Conj? SentP)+
# NP → Det? AdjP+ (N | PPron) (Nest? PP)+ (Nest? RelP)+

# VP → Aux? AdjP+ V
# IVP → AdjP+ IV

# AdjP → Adv? Adj
# PP → P NP
# RelP → RPron VP
