[package]
name = "systean-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "WebAssembly bindings for the Systean language engine"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde.workspace = true
serde_json.workspace = true
systean-core = { path = "../systean-core" }
wasm-bindgen.workspace = true
