[[letters]]
symbol = "a"
pronunciation = "a"
_type = "vowel"

[[letters]]
symbol = "b"
pronunciation = "b"
_type = "consonant"

[[letters]]
symbol = "d"
pronunciation = "d"
_type = "consonant"

[[letters]]
symbol = "e"
pronunciation = "e"
_type = "vowel"

[[letters]]
symbol = "f"
pronunciation = "f"
_type = "consonant"

[[letters]]
symbol = "g"
pronunciation = "g"
_type = "consonant"

[[letters]]
symbol = "h"
pronunciation = "x"
_type = "consonant"

[[letters]]
symbol = "i"
pronunciation = "i"
_type = "vowel"

[[letters]]
symbol = "j"
pronunciation = " ê"
_type = "consonant"

[[letters]]
symbol = "k"
pronunciation = "k"
_type = "consonant"


[[letters]]
symbol = "l"
pronunciation = "l"
_type = "consonant"

[[letters]]
symbol = "m"
pronunciation = "m"
_type = "consonant"

[[letters]]
symbol = "n"
pronunciation = "n"
_type = "consonant"

[[letters]]
symbol = "o"
pronunciation = "o"
_type = "vowel"

[[letters]]
symbol = "p"
pronunciation = "p"
_type = "consonant"

[[letters]]
symbol = "r"
pronunciation = "r"
_type = "consonant"

[[letters]]
symbol = "s"
pronunciation = "s"
_type = "consonant"

[[letters]]
symbol = "t"
pronunciation = "t"
_type = "consonant"

[[letters]]
symbol = "u"
pronunciation = "u"
_type = "vowel"

[[letters]]
symbol = "v"
pronunciation = "v"
_type = "consonant"

[[letters]]
symbol = "y"
pronunciation = "j"
_type = "consonant"

[[letters]]
symbol = "z"
pronunciation = "z"
_type = "consonant"
